### ISSUE TITLE
problem with Mutlisource example

### ISSUE THREAD

**Issue by jingpe** [EnoxSoftware/KinectWithOpenCVForUnitySample#1]
hello .. when i run the example, the follow error is logged from the console.

IndexOutOfRangeException: Array index is out of range.
MultiSourceFrameSample.Update () (at Assets/OpenCVForUnity/Samples/KinectWithOpenCVForUnitySample/MultiSourceFrameSample.cs:170)

**Comment by jingpe** [comment]
I solve it by..

line 170:
int tmp = ((int)depthSpacePoints [index].X + (int)depthSpacePoints [index].Y * depthWidth < 0) ? 0 : (int)depthSpacePoints [index].X + (int)depthSpacePoints [index].Y * depthWidth;

				if (bodyIndexData [tmp] == 255) {
					maskData [index] = 0;
				} else {
					maskData [index] = 255;
				}

**Comment by EnoxSoftware** [comment]
Thank you!!:+1:
